// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtangOkgury1x36cuPYooJxrBxLnQvDxI',
    appId: '1:780667367141:web:f61a1c0412942a58db2e0c',
    messagingSenderId: '780667367141',
    projectId: 'botbrain-58e35',
    authDomain: 'botbrain-58e35.firebase.com',
    storageBucket: 'botbrain-58e35.apps-pot.com',
    measurementId: 'G-LMZKMW7CJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSynbspTDfMHUWUZGbRwR3ih_yI9qej-RjA',
    appId: '1:780667367141:android:3d870f7d08cf1d90db2e0c',
    messagingSenderId: '780667367141',
    projectId: 'botbrain-58e35',
    storageBucket: 'botbrain-58e35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQafFzDTT__gxeV1WKvfU0dXuPFxpophU',
    appId: '1:780667367141:ios:335f2b38ca65e52cdb2e0c',
    messagingSenderId: '780667367141',
    projectId: 'botbrain-58e35',
    storageBucket: 'botbrain-58e35.appspot.com',
    iosClientId: '780667367141-qkutjg1vu17i22j8tgrvqgnb6jf36197.apps.googleusercontent.com',
    iosBundleId: 'com.example.botBrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQafFzDTT__gxeV1WKvfU0dXuPFxpophU',
    appId: '1:780667367141:ios:335f2b38ca65e52cdb2e0c',
    messagingSenderId: '780667367141',
    projectId: 'botbrain-58e35',
    storageBucket: 'botbrain-58e35.appspot.com',
    iosClientId: '780667367141-qkutjg1vu17i22j8tgrvqgnb6jf36197.apps.googleusercontent.com',
    iosBundleId: 'com.example.botBrain',
  );
}
